# Generated by Django 4.2.4 on 2023-08-17 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_product_status_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('deleted', 'Deleted'), ('waitingapproval', 'Waiting approval'), ('active', 'Active'), ('draft', 'Draft')], default='active', max_length=50),
        ),
    ]
