# Generated by Django 4.2.4 on 2023-08-18 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_product_average_rating_alter_product_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('waitingapproval', 'Waiting approval'), ('draft', 'Draft'), ('deleted', 'Deleted')], default='active', max_length=50),
        ),
    ]
