# Generated by Django 4.2.4 on 2023-08-26 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_product_tags_alter_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('draft', 'Draft'), ('waitingapproval', 'Waiting approval'), ('deleted', 'Deleted')], default='active', max_length=50),
        ),
    ]
