# Generated by Django 3.2.20 on 2023-09-01 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_alter_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('waitingapproval', 'Waiting approval'), ('deleted', 'Deleted'), ('active', 'Active')], default='active', max_length=50),
        ),
    ]
