# Generated by Django 3.2.20 on 2023-09-01 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('deleted', 'Deleted'), ('waitingapproval', 'Waiting approval'), ('active', 'Active')], default='active', max_length=50),
        ),
    ]
