# Generated by Django 3.2.20 on 2023-09-02 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_alter_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('deleted', 'Deleted'), ('active', 'Active'), ('waitingapproval', 'Waiting approval'), ('draft', 'Draft')], default='active', max_length=50),
        ),
    ]
