# Generated by Django 3.2.20 on 2024-01-18 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_alter_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('waitingapproval', 'Waiting approval'), ('deleted', 'Deleted'), ('draft', 'Draft'), ('active', 'Active')], default='active', max_length=50),
        ),
    ]
